import SEOHead from '../../components/SEOHead';
import Logo from '../../components/Logo';

export default function PrivacyPage() {
  return (
    <>
      <SEOHead
        title="Privacy Policy - LoonaFlow AI | How We Use Your Data"
        description="Learn about how LoonaFlow AI collects, uses, and protects your personal information and data privacy practices."
        keywords={[
          "loonaflow privacy policy",
          "data protection",
          "cookie policy",
          "privacy practices",
          "loonaflow ai privacy",
          "user data protection",
          "GDPR compliance"
        ]}
        canonical="https://loonaflow.app/privacy"
      />
      <div className="min-h-screen bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50">
        {/* Navigation Header */}
        <nav className="bg-white/20 backdrop-blur-md border-b border-white/30">
          <div className="max-w-6xl mx-auto px-4 py-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between">
              <a href="/" className="flex items-center">
                <Logo size="md" />
              </a>
              <div className="flex items-center gap-6 text-sm">
                <a href="/" className="text-slate-700 hover:text-slate-900 transition-colors">
                  Home
                </a>
                <a href="/pricing" className="text-slate-700 hover:text-slate-900 transition-colors">
                  Pricing
                </a>
                <a href="/contact" className="text-slate-700 hover:text-slate-900 transition-colors">
                  Contact
                </a>
                <a href="/articles" className="text-slate-700 hover:text-slate-900 transition-colors">
                  Articles
                </a>
                <a href="/terms" className="text-slate-700 hover:text-slate-900 transition-colors">
                  Terms
                </a>
              </div>
            </div>
          </div>
        </nav>

        <div className="max-w-4xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
          <div className="bg-white/40 backdrop-blur-md rounded-2xl p-8 ring-1 ring-white/30 shadow-lg shadow-purple-100/50">
            <h1 className="text-4xl font-bold text-slate-900 mb-8">📑 LoonaFlow AI – Privacy Policy</h1>
            
            <div className="prose prose-slate max-w-none">
              <p className="text-lg text-slate-700 mb-6">
                Last updated: August 25, 2025
              </p>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">1. Information We Collect</h2>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li><strong>Account data:</strong> Name, email, company info, billing details</li>
                  <li><strong>Usage data:</strong> Interactions with our Service, analytics</li>
                  <li><strong>Lead/contact data:</strong> Business contacts uploaded or generated by users (LoonaFlow processes these only as a processor)</li>
                  <li><strong>Cookies:</strong> For authentication, analytics, personalization</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">2. Lawful Basis for Processing</h2>
                <p className="text-slate-700 mb-4">
                  We process personal data under GDPR on the following bases:
                </p>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li><strong>To provide the Service:</strong> Contract</li>
                  <li><strong>To provide support & security:</strong> Legitimate Interest</li>
                  <li><strong>For marketing communications:</strong> Consent or Legitimate Interest</li>
                  <li><strong>For lead/contact data provided by users:</strong> Legitimate Interest of users (controllers)</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">3. How We Use Your Information</h2>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li>To deliver and maintain the Service</li>
                  <li>To process payments and provide customer support</li>
                  <li>To improve features and develop new ones</li>
                  <li>To ensure security and prevent abuse</li>
                  <li>To send users service-related communications</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">4. Cookies</h2>
                <p className="text-slate-700 mb-4">
                  We use:
                </p>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li><strong>Essential cookies</strong> (login/session management)</li>
                  <li><strong>Analytics cookies</strong> (usage statistics)</li>
                  <li><strong>Functional cookies</strong> (preferences, personalization)</li>
                </ul>
                <p className="text-slate-700 mb-4">
                  You can manage cookies via your browser settings.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">5. Data Sharing</h2>
                <p className="text-slate-700 mb-4">
                  We do not sell your data. We may share it only with:
                </p>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li>Trusted service providers (e.g., hosting, Outscraper, email providers)</li>
                  <li>Legal authorities, when required</li>
                  <li>In case of business transfers (e.g., merger or acquisition)</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">6. International Transfers</h2>
                <p className="text-slate-700 mb-4">
                  If data is transferred outside the EU (e.g., to the US), we use Standard Contractual Clauses (SCCs) or equivalent safeguards.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">7. Data Retention</h2>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li><strong>Account data:</strong> kept while your account is active, or as legally required</li>
                  <li><strong>Lead/contact data:</strong> retained only while your subscription is active or until deleted by you</li>
                  <li><strong>Suppression lists:</strong> retained to respect unsubscribe requests</li>
                </ul>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">8. Your Rights</h2>
                <p className="text-slate-700 mb-4">
                  Under GDPR, you have the right to:
                </p>
                <ul className="list-disc pl-6 text-slate-700 mb-4">
                  <li>Access your personal data</li>
                  <li>Correct inaccuracies</li>
                  <li>Request deletion ("right to be forgotten") - You may request deletion at any time, and we will erase your data within 30 days.</li>
                  <li>Restrict or object to processing</li>
                  <li>Data portability</li>
                  <li>Withdraw consent at any time</li>
                </ul>
                                 <p className="text-slate-700 mb-4">
                   Requests can be made at hello@loonaflow.app
                 </p>
                 <p className="text-slate-700 mb-4">
                   Our standard DPA is available on request at hello@loonaflow.app
                 </p>
                <p className="text-slate-700 mb-4">
                  If you believe your data protection rights have been violated, you may lodge a complaint with the Czech Data Protection Authority (Úřad pro ochranu osobních údajů, www.uoou.cz) or with your local supervisory authority within the EU.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">9. Security</h2>
                <p className="text-slate-700 mb-4">
                  We use appropriate security measures, including encryption, access controls, and monitoring. However, no system is 100% secure.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">10. Children's Data</h2>
                <p className="text-slate-700 mb-4">
                  The Service is not intended for children under 16. We do not knowingly collect their data.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">11. Changes to this Policy</h2>
                <p className="text-slate-700 mb-4">
                  We may update this Privacy Policy. Updates will be posted here with the new date. For significant changes, we will notify you via email or in-app.
                </p>
              </section>

              <section className="mb-8">
                <h2 className="text-2xl font-semibold text-slate-900 mb-4">12. Contact Information</h2>
                <div className="bg-slate-50 rounded-lg p-4">
                  <p className="text-slate-700">
                    <strong>Email:</strong> hello@loonaflow.app<br />
                    <strong>Address:</strong> LoonaFlow AI<br />
                    <strong>Subject:</strong> Privacy Policy Inquiry
                  </p>
                </div>
              </section>
            </div>
          </div>

          {/* Footer Navigation */}
          <div className="mt-12 text-center">
            <div className="bg-white/20 backdrop-blur-md rounded-2xl p-6 ring-1 ring-white/30">
              <p className="text-slate-600 mb-4">Need help or have questions?</p>
              <div className="flex flex-wrap justify-center gap-4 text-sm">
                <a href="/" className="text-violet-600 hover:text-violet-700 font-medium">
                  ← Back to Home
                </a>
                <a href="/contact" className="text-violet-600 hover:text-violet-700 font-medium">
                  Contact Support
                </a>
                <a href="/terms" className="text-violet-600 hover:text-violet-700 font-medium">
                  Terms of Service
                </a>
                <a href="/pricing" className="text-violet-600 hover:text-violet-700 font-medium">
                  View Pricing
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
